keys:
  - &danielfullmer FA0ED54AE0DBF4CDC4B4FEADD1481BC2EF6B0CB0
  - &danielfullmer-offlinekey 7242A6FEF237A429E981576F6EDF0AEEA2D9FA5D
  - &bellman 2CDAFDCB8F320753F59E1B31EF942D14867FCACA
  - &gauss 17577213896ED87177A71D00A4A02C44B781588E
  - &banach 50FA682AF4D40AC551963CA0971337F9A34AB5AB
  - &laplace ED8A6848AE92FD517EBF44673FED6D228CA9F576
  - &riemann age13mfy89qgy00yq4pvm0grt3ncexh5sl0xwuu0hzjdjjw0wzjs244qtxwtsc
  - &noether age1tmmp92pmf7ngshe65e7cmfllu9gnvcy4weuxckvs8wuzpf4uscvst46kp5
  - &viterbi age14wp59ju8r43lqzrrv94s5w4y7rwjp960meezjw3xfhsfmkphvp0qfrjyqu
creation_rules:
  - path_regex: machines/bellman/secrets/[^/]+$
    key_groups:
    - pgp:
      - *danielfullmer
      - *danielfullmer-offlinekey
      - *bellman
  - path_regex: machines/gauss/secrets/[^/]+$
    key_groups:
    - pgp:
      - *danielfullmer
      - *danielfullmer-offlinekey
      - *gauss
  - path_regex: machines/banach/secrets/[^/]+$
    key_groups:
    - pgp:
      - *danielfullmer
      - *danielfullmer-offlinekey
      - *banach
  - path_regex: machines/laplace/secrets/[^/]+$
    key_groups:
    - pgp:
      - *danielfullmer
      - *danielfullmer-offlinekey
      - *laplace
  - path_regex: machines/riemann/secrets/[^/]+$
    key_groups:
    - pgp:
      - *danielfullmer
      - *danielfullmer-offlinekey
      age:
      - *riemann
  - path_regex: machines/noether/secrets/[^/]+$
    key_groups:
    - pgp:
      - *danielfullmer
      - *danielfullmer-offlinekey
      age:
      - *noether
  - path_regex: machines/viterbi/secrets/[^/]+$
    key_groups:
    - pgp:
      - *danielfullmer
      - *danielfullmer-offlinekey
      age:
      - *viterbi
  - path_regex: secrets/[^/]+$
    key_groups:
    - pgp:
      - *danielfullmer
      - *danielfullmer-offlinekey
      - *bellman
      - *gauss
      - *banach
      - *laplace
      age:
      - *riemann
      - *noether
      - *viterbi
