# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "browserpass-${version}";
  version = "20170109-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "69c41b36818907bb4c41b163abfcaff09b718002";

  goPackagePath = "github.com/dannyvankooten/browserpass";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/dannyvankooten/browserpass";
    sha256 = "1hd9yjzw03vwcmd0szbaf2n0wp31k5747vp1ds288agvm3h90njf";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
