# This file was generated by https://github.com/kamilchm/go2nix v1.2.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "browserpass-unstable-${version}";
  version = "2017-03-20";
  rev = "51579bc12eda96d40b8dc788bde2a24eb7d7bf2c";

  goPackagePath = "github.com/dannyvankooten/browserpass";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/dannyvankooten/browserpass";
    sha256 = "16cbkl2xwdm6iid65hayajx9349yagl5m6j1ppxkgz0zcwap1iv7";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
