# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/mattn/go-zglob";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-zglob";
      rev = "1783ae1a9f7ff3a79240e8c249d8b575d70a6528";
      sha256 = "0g4ih6swqpq0bqwsv5mv8ymicgr92xh9i6sm1793lqwb63x8ga1x";
    };
  }
]
