# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "netgear_exporter-unstable-${version}";
  version = "2020-04-27";
  rev = "0d0f2f0927ef9d007f9030c9f5146a34ea98f2f9";

  goPackagePath = "github.com/DRuggeri/netgear_exporter";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/DRuggeri/netgear_exporter";
    sha256 = "0z3r3d5qy7af1ynjkazhjqs3jc7arkv0fx0ck3zpn9zk6c03shzz";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
