#! /bin/sh

DIR="$(dirname $0)"

export PANEL_FIFO="/tmp/panel_fifo"
export PANEL_HEIGHT="20"

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
conky -c $DIR/conkyrc > "$PANEL_FIFO" &

source "$DIR/panel_colors"

${DIR}/panel_bar < "$PANEL_FIFO" | lemonbar \
        -f "DejaVu Sans Mono for Powerline" -f "FontAwesome" \
        -F "$COLOR_FOREGROUND" \
        -B "$COLOR_BACKGROUND" \
    | while read line; do eval "$line"; done &

wait
