#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config focused_border_color red
bspc config presel_border_color green
bspc config window_gap          5
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
