{ emacsWithPackages }:
# See also: https://github.com/syl20bnr/spacemacs/issues/7813#issuecomment-297047175
emacsWithPackages (ep: with ep; [
  ace-jump-helm-line
  ace-link
  ace-window
  ac-ispell
  adaptive-wrap
  aggressive-indent
  alert
  anaconda-mode
  anzu
  #archives
  async
  auctex
  auctex-latexmk
  auto-compile
  auto-complete
  auto-dictionary
  auto-highlight-symbol
  auto-yasnippet
  avy
  bind-key
  bind-map
  cider
  cider-eval-sexp-fu
  clean-aindent-mode
  clj-refactor
  clojure-mode
  clojure-snippets
  column-enforce-mode
  company
  company-anaconda
  company-auctex
  company-nixos-options
  company-statistics
  cython-mode
  dash
  define-word
  diff-hl
  diminish
  dumb-jump
  edn
  ein
  elisp-slime-nav
  epl
  eshell-prompt-extras
  eshell-z
  esh-help
  eval-sexp-fu
  evil
  evil-anzu
  evil-args
  evil-ediff
  evil-escape
  evil-exchange
  evil-iedit-state
  evil-indent-plus
  evil-lisp-state
  evil-magit
  evil-matchit
  evil-mc
  evil-nerd-commenter
  evil-numbers
  evil-search-highlight-persist
  evil-surround
  evil-tutor
  #evil-unimpaired
  evil-visual-mark-mode
  evil-visualstar
  exec-path-from-shell
  expand-region
  eyebrowse
  f
  fancy-battery
  fill-column-indicator
  flx
  flx-ido
  flycheck
  flycheck-pos-tip
  flyspell-correct
  flyspell-correct-helm
  fringe-helper
  fuzzy
  gh
  gh-md
  gist
  gitattributes-mode
  git-commit
  gitconfig-mode
  git-gutter
  git-gutter-fringe
  git-gutter-fringe-plus
  git-gutter-plus
  github-browse-file
  github-clone
  github-search
  gitignore-mode
  git-link
  git-messenger
  git-timemachine
  gntp
  #gnupg
  gnuplot
  golden-ratio
  google-translate
  goto-chg
  helm
  helm-ag
  helm-company
  helm-core
  helm-c-yasnippet
  helm-descbinds
  helm-flx
  helm-gitignore
  helm-make
  helm-mode-manager
  helm-nixos-options
  helm-projectile
  helm-pydoc
  helm-swoop
  helm-themes
  help-fns-plus
  hide-comnt
  highlight
  highlight-indentation
  highlight-numbers
  highlight-parentheses
  hl-todo
  ht
  htmlize
  hungry-delete
  hydra
  hy-mode
  iedit
  indent-guide
  inflections
  info-plus
  #link-hint
  linum-relative
  live-py-mode
  log4e
  logito
  lorem-ipsum
  macrostep
  magit
  magit-gh-pulls
  magit-gitflow
  magit-popup
  markdown-mode
  markdown-toc
  marshal
  mmm-mode
  monokai-theme
  move-text
  multiple-cursors
  multi-term
  neotree
  nix-mode
  nixos-options
  open-junk-file
  org-bullets
  org-download
  orgit
  org-plus-contrib
  org-pomodoro
  org-present
  org-projectile
  packed
  paradox
  paredit
  parent-mode
  pcache
  pcre2el
  pdf-tools
  peg
  persp-mode
  pip-requirements
  pkg-info
  popup
  popwin
  pos-tip
  powerline
  projectile
  pyenv-mode
  py-isort
  pytest
  pythonic
  pyvenv
  queue
  rainbow-delimiters
  request
  restart-emacs
  s
  seq
  shell-pop
  smartparens
  smeargle
  solarized-theme
  spaceline
  spinner
  tablist
  toc-org
  undo-tree
  use-package
  uuidgen
  vi-tilde-fringe
  volatile-highlights
  websocket
  which-key
  winum
  with-editor
  ws-butler
  xterm-color
  yapfify
  yasnippet
  zenburn-theme
])
